CREATE TABLE "Permission" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(100) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "ResourceType" character varying(50) NOT NULL,
    "Group" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Permission" PRIMARY KEY ("Id")
);


CREATE TABLE "Permissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "Group" character varying(50) NOT NULL,
    "ResourceType" character varying(50),
    "ResourceName" character varying(50),
    "Action" character varying(50),
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Permissions" PRIMARY KEY ("Id")
);


CREATE TABLE "Roles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(50) NOT NULL,
    "Description" character varying(200) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" character varying(50),
    "UpdatedBy" character varying(50),
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);


CREATE TABLE "RolePermission" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_RolePermission" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolePermission_Permission_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permission" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermission_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "RolePermissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_RolePermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RolePermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RolePermissions_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);


CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Username" character varying(50) NOT NULL,
    "PasswordHash" text NOT NULL,
    "IsAdmin" boolean NOT NULL DEFAULT FALSE,
    "LastLoginAt" timestamp with time zone,
    "Sicil" character varying(50) NOT NULL,
    "RoleId" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" character varying(50),
    "UpdatedBy" character varying(50),
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE SET NULL
);


CREATE TABLE "ActivityLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "Username" character varying(50) NOT NULL,
    "ActivityType" character varying(50) NOT NULL,
    "Description" character varying(500) NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "AdditionalInfo" text,
    "IsSynchronized" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_ActivityLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ActivityLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);


CREATE TABLE "AuditLogs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Action" character varying(50) NOT NULL,
    "EntityType" character varying(100) NOT NULL,
    "EntityId" character varying(50) NOT NULL,
    "UserId" character varying(50) NOT NULL,
    "Path" character varying(200) NOT NULL,
    "Details" text NOT NULL,
    "UserId1" integer,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AuditLogs_Users_UserId1" FOREIGN KEY ("UserId1") REFERENCES "Users" ("Id")
);


CREATE TABLE "UserPermission" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    "IsGranted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "CreatedBy" text,
    "UpdatedBy" text,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_UserPermission" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserPermission_Permission_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permission" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserPermission_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


CREATE TABLE "UserPermissions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "PermissionId" integer NOT NULL,
    "IsGranted" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_UserPermissions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserPermissions_Permissions_PermissionId" FOREIGN KEY ("PermissionId") REFERENCES "Permissions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserPermissions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);


INSERT INTO "Roles" ("Id", "CreatedAt", "CreatedBy", "Description", "Name", "UpdatedAt", "UpdatedBy")
VALUES (1, TIMESTAMPTZ '2025-03-01T00:00:00Z', NULL, 'Administrator role with full access', 'Admin', NULL, NULL);


INSERT INTO "Users" ("Id", "CreatedAt", "CreatedBy", "IsAdmin", "LastLoginAt", "PasswordHash", "RoleId", "Sicil", "UpdatedAt", "UpdatedBy", "Username")
VALUES (1, TIMESTAMPTZ '2025-03-01T00:00:00Z', NULL, TRUE, NULL, '$2a$11$ij4DH2oHJIgakH3QZS94Uu1/jandJqMjWZtQB8B5.JoK4zrBd2Lhu', 1, '', NULL, NULL, 'admin');


CREATE INDEX "IX_ActivityLogs_UserId" ON "ActivityLogs" ("UserId");


CREATE INDEX "IX_AuditLogs_UserId1" ON "AuditLogs" ("UserId1");


CREATE UNIQUE INDEX "IX_Permission_Name" ON "Permission" ("Name");


CREATE UNIQUE INDEX "IX_Permissions_Name" ON "Permissions" ("Name");


CREATE INDEX "IX_RolePermission_PermissionId" ON "RolePermission" ("PermissionId");


CREATE INDEX "IX_RolePermission_RoleId" ON "RolePermission" ("RoleId");


CREATE INDEX "IX_RolePermissions_PermissionId" ON "RolePermissions" ("PermissionId");


CREATE UNIQUE INDEX "IX_RolePermissions_RoleId_PermissionId" ON "RolePermissions" ("RoleId", "PermissionId");


CREATE UNIQUE INDEX "IX_Roles_Name" ON "Roles" ("Name");


CREATE INDEX "IX_UserPermission_PermissionId" ON "UserPermission" ("PermissionId");


CREATE INDEX "IX_UserPermission_UserId" ON "UserPermission" ("UserId");


CREATE INDEX "IX_UserPermissions_PermissionId" ON "UserPermissions" ("PermissionId");


CREATE UNIQUE INDEX "IX_UserPermissions_UserId_PermissionId" ON "UserPermissions" ("UserId", "PermissionId");


CREATE INDEX "IX_Users_RoleId" ON "Users" ("RoleId");


CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");


SELECT setval(
    pg_get_serial_sequence('"Roles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Roles") + 1,
        nextval(pg_get_serial_sequence('"Roles"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Users"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Users") + 1,
        nextval(pg_get_serial_sequence('"Users"', 'Id'))),
    false);


